#ifndef _MOUSE_EVENT_RECORD_H_
#define _MOUSE_EVENT_RECORD_H_
//#if _MSC_VER > 1000
//#pragma once
//#endif

#define LIBSPEC __declspec(dllexport)

   LIBSPEC BOOL InstallHook(HWND hWnd);
   LIBSPEC BOOL UnInstallHook(HWND hWnd);
#undef LIBSPEC

#define UWM_MOUSEMOVE_MSG ("UWM_MOUSEMOVE_USER_MSG")
#define UWM_MOUSELBUTTONUP_MSG ( "UWM_MOUSELBUTTONUP_USER_MSG" )
#define UWM_MOUSELBUTTONDOWN_MSG ( "UWM_MOUSELBUTTONDOWN_USER_MSG" )
#define UWM_MOUSERBUTTONUP_MSG ( "UWM_MOUSERBUTTONUP_USER_MSG" )
#define UWM_MOUSERBUTTONDOWN_MSG ( "UWM_MOUSERBUTTONDOWN_USER_MSG" )
#define UWM_MOUSELDBCLICK_MSG ( "UWM_MOUSERBUTTONDOWN_USER_MSG" )

#endif // _DEFINED_44E531B1_14D3_11d5_A025_006067718D04
